### ISSUE TITLE
Bug: $clear not working correctly

### ISSUE THREAD

**Issue by AstrooKai** [aoijs/aoi.js#549]
### Bug Type

Function

### Bugged Function

```js
$clear[channelID;amount;filter?;returnCount?]
```

### Version of aoi.js

v6.6.1

### Version of Node.js

v21.4.0 (Current)

### Excepted Output

The function `$clear` seems to be somewhat not working correctly, learning that the function does not execute nor return an error when it does not work as intended for its use. The function was expected to perform according to the parameters provided to it, but a bug seemed to be interfering with the process.

For instance, performing `$clear[$channelID;1;notpinned;true]` should delete one message that is not pinned, but in reality, executing this code does nothing, with no errors logged in the console. The following is the list of other code executions tested that didn't work as expected.
```php
1) $clear[$channelID;1;notpinned;true/false]
2) $clear[$channelID;1;$authorID;true/false]
3) $clear[$channelID;1;;true/false]
4) $clear[$channelID;1;user_id;true/false]
5) $clear[$channelID;1]
```
The code above doesn't work on any given amount of messages and conditions for the `returnCount?` parameter. Considering that the `filter?` parameter is optional, leaving this parameter empty also does not work correctly. Weirdly, the code `$clear[$channelID;1]` does delete messages, but it only deletes messages from the author, and despite putting `1` in the `amount` parameter, the bot deletes two messages from the author.

```php
$clear[$channelID;1;everyone;true/false]
```
On the other hand, this one partially works. But setting the `returnCount?` parameter to `true` doesn't return the count of messages that have been deleted. As mentioned earlier, the `filter?` cannot be left blank since doing so would result in the function not executing.

While this was only tested on my end, it is unclear whether other users are facing the exact same issue. However, there were reports in the Discord server regarding this function not working properly on their end.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Faf4a** [comment]
@AstrooKai should be fixed in the Github version, please try it and let me know.

`npm i github:AkaruiDevelopment/aoi.js#v6`

**Comment by AstrooKai** [comment]
@Faf4a I just tested the function with the GitHub version, and the function is still not working correctly.

```js
$clear[$channelID;1] // works fine even with various amount of messages
$clear[$channelID;1;everyone;true] // deletes messages but does not return the count of messages deleted
$clear[$channelID;1;bots;true/false] // deletes two messages instead of one and setting the returnCount? to true doesn't return the count
$clear[$channelID;1;notpinned;true/false] // no action happening
```
These were the parameters I tested with this function using the GitHub version and considering the results, it seems that the issue continues. During these, no errors are being logged or sent to the channel.

**Comment by Faf4a** [comment]
Will see what's the cause.

**Comment by AstrooKai** [comment]
Looking forward to it, thanks.

**Comment by Faf4a** [comment]
Should be fixed with b4436f5 let me know if not.
